### ISSUE TITLE
Comments are not parsed correctly?

### ISSUE THREAD

**Issue by mueller-jens** [bkiers/python3-parser#12]
I try to parse a python program where i have an inline comment like:

```
import logging
import sys
from asyncio import sleep

CONFIG = {
  "key1": "Value1", #Description of config parameter 1
  "key2": 1.23,
  "key3": 0x1FFFFFFF
}

```

where i also need the comment. So i removed the "COMMENT" from the skiped expressions:
```

SKIP_
 : ( SPACES  ) -> skip
 ;

```

When i now try to parse these code, I get the following warnings:
```

line 7:20 mismatched input '#' expecting '}'
line 7:33 no viable alternative at input 'of'
line 7:36 no viable alternative at input 'config'
line 7:43 no viable alternative at input 'parameter'
line 7:53 no viable alternative at input '1'
line 8:2 no viable alternative at input '"key2"'
line 8:14 mismatched input ',' expecting {NEWLINE, ';'}
line 10:0 extraneous input '}' expecting {NEWLINE, ';'}
```

Is there anything i miss?

**Comment by bkiers** [comment]
I just saw this. When there's no `@bkiers` in an issue or PR, chances are big I miss it.

> where i also need the comment. So i removed the "COMMENT" from the skiped expressions:

No, you can't just do that. Doing so will cause all COMMENTs to be pushed to the parser, meaning you would need to litter all the parser rules with these tokens: not something that is doable.
